### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Url-Shortener-Frontend#2]
Create a file named **contribution.md** and use this [template](https://github.com/faradayafrica/Faraday-event/blob/main/contributing.md) to update it. You don't have to modify anything.

**Comment by vikash485** [comment]
Can I take up this issue @devgenix ?

**Comment by devgenix** [comment]
> Can I take up this issue @devgenix ?

Yes you can, I'll assign it to you now.

**Comment by vikash485** [comment]
I have submitted a pr for this, please check

**Comment by devgenix** [comment]
Closed by #3
