### ISSUE TITLE
Add Dark theme and a toggle

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Url-Shortener-Frontend#4]
Using these colors <br> 
![Frame 361](https://user-images.githubusercontent.com/55883854/193599188-fda20d3d-53c9-4498-8793-c8eefb4673bc.png)

```
#333B47
#606773
#E3E7F4
```

Modify the background color to use the dark color code provided and add a toggle for dark/light theme.

**Comment by Candy505** [comment]
@devgenix I would like to contribute by making these changes, kindly assign this to me.

**Comment by darshikaguptaa** [comment]
Hey I am Interested in working in this issue.
Please assign it to me.

**Comment by devgenix** [comment]
> Hey @devgenix @faradayadmin I am Interested in working in this issue. Please assign it to me.

Sorry, @Candy505 requested for it first.

**Comment by devgenix** [comment]
> @devgenix I would like to contribute by making these changes, kindly assign this to me.

I have now assigned it to you.

**Comment by Candy505** [comment]
@devgenix Hey ! Kindly review this, I'm attaching snapshots.
 
**Dark mode**
![Screenshot (303)](https://user-images.githubusercontent.com/87769883/193882602-7eb315c6-5323-4d8d-b598-1e0fe2c1f739.png)

**Light Mode**
![Screenshot (302)](https://user-images.githubusercontent.com/87769883/193882622-e34c8985-f2f2-49ac-9513-d65f69b315fc.png)

**Comment by devgenix** [comment]
> @devgenix Hey ! Kindly review this, I'm attaching snapshots.
> 
> **Dark mode** ![Screenshot (303)](https://user-images.githubusercontent.com/87769883/193882602-7eb315c6-5323-4d8d-b598-1e0fe2c1f739.png)
> 
> **Light Mode** ![Screenshot (302)](https://user-images.githubusercontent.com/87769883/193882622-e34c8985-f2f2-49ac-9513-d65f69b315fc.png)

It's looks good. Can I see screenshots of it on Mobile?

**Comment by devgenix** [comment]
@Candy505 If you can't provide that, please create a pull request for this so that I can review the deploy preview.

**Comment by Candy505** [comment]
@devgenix My apologies for the late response and thankyou for waiting patiently. I have created the pull request.

**Comment by devgenix** [comment]
> @devgenix My apologies for the late response and thankyou for waiting patiently. I have created the pull request.

It's fine, I'll review it now, thank you.
